### PR TITLE
issue 39 - Introduce -IgnoreJDKClasses option for ignoring JDK classes

### PR DESCRIPTION
**Pull request by scottmarlow**
Introduce -IgnoreJDKClasses option for ignoring JDK classes and treat (legacy) -IgnoreJDKClass [jdkclass] option the same as -IgnoreJDKClasses

### CODE REVIEW

**Comment by jamezp** [comment]
I don't know if we should be treating the `-IgnoreJDKClass` the same TBH. I don't really see a good reason for that other than it would possibly benefit runs on older TCK's. However, there could be valid reasons for only wanting to ignore certain types.

I'll wait for others to chime in on that though :)

**Comment by scottmarlow** [comment]
> I don't know if we should be treating the `-IgnoreJDKClass` the same TBH. I don't really see a good reason for that other than it would possibly benefit runs on older TCK's. However, there could be valid reasons for only wanting to ignore certain types.
> 
> I'll wait for others to chime in on that though :)

There weren't any use cases that involved specifying a partial set of JDK dependencies to exclude as the entire set of JDK dependencies needed to be specified.  

However, there are two use cases that are important (I think):

- Only the `-IgnoreJDKClass` was specified with the 2.3 release meaning that all JDK classes should be ignored.
- `-IgnoreJDKClass jdkClassName` was specified with the 2.2 release where each JDK class that the target SPEC API depends on is specified.  The entire set of JDK (direct) dependencies was always specified.

More details:
As far as I know, we (Jakarta EE community) are the only ones using the -IgnoreJDKClass <classname> option which was originally added via https://github.com/jtulach/netbeans-apitest/pull/2 for the purpose of excluding all JDK classes as suggested by tracking issue https://github.com/jakartaee/platform-tck/issues/156

It was painful for each TCK to list the individual JDKClass names to ignore due to subsequent Java SE releases that added additional JDK classes that also needed to be in the list.

**Comment by scottmarlow** [comment]
> I don't know if we should be treating the `-IgnoreJDKClass` the same TBH. I don't really see a good reason for that other than it would possibly benefit runs on older TCK's. However, there could be valid reasons for only wanting to ignore certain types.
> 

The other reason is so that Jakarta EE TCKs that upgrade to the 2.4 release don't have to change their code but they could switch to `IgnoreJDKClasses`.

**Comment by jamezp** [comment]
I do understand those arguments and I don't want to block the PR on this as it at least allows older TCK's to use the newer signature test releases. However, there could be valid cases where `-IgnoreJDKClass` is used. I don't know one, but that doesn't mean there isn't one.

We could treat `-IgnoreJDKClass` with no value the same as `-IgnoreJDKClasses` though.

**Comment by scottmarlow** [comment]
> I do understand those arguments and I don't want to block the PR on this as it at least allows older TCK's to use the newer signature test releases. However, there could be valid cases where `-IgnoreJDKClass` is used. I don't know one, but that doesn't mean there isn't one.
> 
> We could treat `-IgnoreJDKClass` with no value the same as `-IgnoreJDKClasses` though.

Thanks James for the useful feedback!  I didn't consider handling the case of `-IgnoreJDKClass` + `a jdkclass name` differently as I was just trying to make both prior cases just work regardless of the approach used.  I think it is fine to tighten the checking up to not allow the inexact case so that we can remove the need to support that now and in the future.

**Pull request merged**
